# Generated by Django 2.2.5 on 2021-06-19 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_maturity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='', max_length=10)),
                ('maturity', models.FloatField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
