# Generated by Django 2.2.5 on 2021-06-19 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CropMaturity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_maturity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 8, 17, 5, 479215, tzinfo=utc)),
        ),
    ]
