# Generated by Django 2.2.5 on 2021-06-19 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CropMaturity', '0002_auto_20210619_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_maturity',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
