# Generated by Django 2.2.5 on 2021-06-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProdInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='up_drop',
            new_name='change_num',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='up_drop_rate',
            new_name='change_ratio',
        ),
    ]
