# Generated by Django 2.2.5 on 2021-06-18 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProdInfo', '0002_auto_20210610_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 13, 31, 12, 462868)),
        ),
    ]
