# Generated by Django 2.2.5 on 2021-06-18 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProdInfo', '0003_auto_20210618_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
