# Generated by Django 2.2.5 on 2021-06-19 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_image',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
