# Generated by Django 2.2.5 on 2021-06-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_maturity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=10)),
                ('maturity', models.FloatField(default=0)),
                ('time', models.DateTimeField(verbose_name='time published')),
            ],
        ),
        migrations.CreateModel(
            name='Environment_monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0)),
                ('light_intensity', models.FloatField(default=0)),
                ('CO_concentration', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('soil_humidity', models.FloatField(default=0)),
                ('precipitation', models.FloatField(default=0)),
                ('time', models.DateTimeField(verbose_name='time published')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=100)),
                ('time', models.DateTimeField(verbose_name='time published')),
            ],
        ),
    ]
