# Generated by Django 2.2.5 on 2021-06-18 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0002_auto_20210618_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_maturity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 13, 31, 12, 464211)),
        ),
        migrations.AlterField(
            model_name='environment_monitor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 13, 31, 12, 463926)),
        ),
        migrations.AlterField(
            model_name='monitor_video',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 13, 31, 12, 463500)),
        ),
    ]
