# Generated by Django 2.2.5 on 2021-06-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0006_auto_20210619_0532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop_maturity',
        ),
    ]
